Prompt: Explain the water cycle.
Response: The water cycle involves evaporation, condensation, and precipitation...

Prompt: Describe photosynthesis.
Response: Photosynthesis is the process by which plants convert sunlight into...
